server:
  port: 8080
  servlet:
    context-path: /
  output:
    ansi:
      enabled: ALWAYS
  oauth2:
    client:
      client-id: '198862669795.646621987428'
      client-secret: 'f97205a076c910e5eb9bbb7b474964a7'
      access-token-uri: 'https://slack.com/api/oauth.access'
      user-authorization-uri: 'https://slack.com/oauth/authorize'
      client-authentication-scheme: 'query'
      scope: 'identify'
      tokenName: 'token'
    resource:
      user-info-uri: 'https://slack.com/api/auth.test'